name: takecare_user
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.2.3+23

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_device_type: ^0.4.0
  get: ^4.6.1
  fluttertoast: ^8.0.6
  shared_preferences: ^2.0.11
  flutter_spinkit: ^5.1.0
  firebase_messaging: ^14.2.5
  flutter_local_notifications: ^13.0.0
  toggle_switch: ^2.0.1
  dotted_border: ^2.0.0+2
#  intl: ^0.16.1
  intl: ^0.17.0-nullsafety.2
  cupertino_radio_choice: ^1.0.2
  otp_text_field: ^1.1.1
  flutter_otp_text_field: ^1.0.0
  extended_tabs: any
  image_picker: ^0.8.6
  buttons_tabbar: ^1.3.2
  http: ^0.13.4
  cloud_firestore: ^4.4.3
  cached_network_image: ^3.2.0
  uuid: ^3.0.6
  firebase_auth: ^4.2.9
  firebase_core: ^2.7.0
  firebase_database: ^10.0.14
  blurrycontainer: 1.0.2
  carousel_slider: ^4.0.0
  sms_autofill: ^2.2.0
  geolocator: ^9.0.2
  url_launcher: ^6.1.6
  change_app_package_name: ^1.1.0
  loading_animation_widget: ^1.2.0+3
  package_info_plus: ^3.0.3
  firebase_remote_config: ^3.0.13
  flutter_cached_pdfview: ^0.4.1
  video_player: ^2.2.7
  line_awesome_flutter: ^2.0.0
  google_maps_flutter: ^2.1.1
  flutter_polyline_points: ^1.0.0
  location: ^4.4.0
  flutter_close_app: ^1.0.0
  omni_datetime_picker: ^1.0.0
  search_map_place_updated: ^0.0.4
  flutter_google_places: ^0.3.0
  google_maps_webservice: ^0.0.20-nullsafety.5
  geocoding: ^2.1.0
  pusher_client: ^2.0.0

  # google_maps_flutter_platform_interface: ^2.2.1
 # google_maps_flutter_android: ^2.1.10

 # google_map_location_picker: ^4.1.7
 # flutter_localizations:
  #  sdk: flutter
 # google_maps_place_picker: ^2.0.0
#
#  barikoi_maps_place_picker:
#    git:
#      url: https://github.com/barikoi/barikoi_map_place_picker.git
#      ref: '57c8aba69ac7690646fe460139740c072e198e63'
#  barikoi_maps_place_picker:
#    git:
#      url: https://github.com/barikoi/barikoi_map_place_picker.git
#      ref: '9128ba9dbbfe2914d30e9ffa4b9834f8c1c7f684'

#  barikoi_api:l,l
#    git: https://github.com/barikoi/barikoi_api_dartlib.git
#      version: 'any'
#  maplibre_gl:
#    git:
#      url: https://github.com/m0nac0/flutter-maplibre-gl.git
#      ref: 0.15.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.png"


flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # example:
  fonts:
    - family: Muli
      fonts:
        - asset: fonts/Mulish-Regular.ttf
        - asset: fonts/Mulish-Bold.ttf
          weight: 700
        - asset: fonts/Mulish-Black.ttf
          weight: 900
        - asset: fonts/Mulish-Light.ttf
          weight: 300
        - asset: fonts/Mulish-SemiBold.ttf
          weight: 600
#     - family: Trajan Pro
#       fonts:
#         - asset: fonts/TrajanPro.ttf
#         - asset: fonts/TrajanPro_Bold.ttf
#           weight: 700
  #
