name: takecare_user
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_device_type: ^0.4.0
  get: ^4.6.1
  fluttertoast: ^8.0.6
  shared_preferences: ^2.0.11
  flutter_spinkit: ^5.1.0
  firebase_messaging: ^11.2.4
  flutter_local_notifications: ^9.2.0
  firebase_core: ^1.10.6
  toggle_switch: ^1.3.0
  dotted_border: ^2.0.0+2


  cupertino_radio_choice: 1.0.0+1
  otp_text_field: ^1.1.1
  flutter_otp_text_field: ^1.0.0
  extended_tabs: any
  image_picker: ^0.8.4+4
  buttons_tabbar: ^1.3.2
  google_maps_flutter: ^2.1.1
  cached_network_image: ^3.2.0
  flutter_launcher_icons: ^0.9.2


  barikoi_maps_place_picker:
    git:
      url: https://github.com/barikoi/barikoi_map_place_picker.git
      ref: '9128ba9dbbfe2914d30e9ffa4b9834f8c1c7f684'
#  barikoi_api:
#    git: https://github.com/barikoi/barikoi_api_dartlib.git
#      version: 'any'


dev_dependencies:
  flutter_launcher_icons: "^0.9.2"
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0



flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.png"


flutter:
  uses-material-design: true



  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
#    - assets/images/success.png
#    - assets/images/profile_setup.png
#    - assets/images/setting.png
#    - assets/images/profile_icon.png
#    - assets/images/leave.png
#    - assets/images/icon.png

  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
