// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1bCImFwzcclPmHnqb3_IafrAau5cjCrE',
    appId: '1:947236785071:web:131fe88d6a0c753fa07d5a',
    messagingSenderId: '947236785071',
    projectId: 'httpstakecareltd',
    authDomain: 'httpstakecareltd.firebaseapp.com',
    storageBucket: 'httpstakecareltd.appspot.com',
    measurementId: 'G-MX88VYHJXP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6-exW_Xct0zjsSRnVmXoQJ9zEaWF9jwI',
    appId: '1:947236785071:android:066f31b52ba29c37a07d5a',
    messagingSenderId: '947236785071',
    projectId: 'httpstakecareltd',
    storageBucket: 'httpstakecareltd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPCbC2zItcRglbDZFIxzObIoSTkMA4xOo',
    appId: '1:947236785071:ios:22e6a543ddbab32fa07d5a',
    messagingSenderId: '947236785071',
    projectId: 'httpstakecareltd',
    storageBucket: 'httpstakecareltd.appspot.com',
    iosClientId: '947236785071-670duo6d4djipnr70a2v3tjut2ihllbt.apps.googleusercontent.com',
    iosBundleId: 'com.example.takecareUser',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPCbC2zItcRglbDZFIxzObIoSTkMA4xOo',
    appId: '1:947236785071:ios:7c37abc43de63cb8a07d5a',
    messagingSenderId: '947236785071',
    projectId: 'httpstakecareltd',
    storageBucket: 'httpstakecareltd.appspot.com',
    iosClientId: '947236785071-ehpl1829n1fcqb20f0vp83qj4bc41nvr.apps.googleusercontent.com',
    iosBundleId: 'com.spontit.takeCareUser',
  );
}
